### ISSUE TITLE
Add credits to usm-debug-menu

### ISSUE THREAD

**Issue by krystalgamer** [AkyrosXD/RaimiHook#1]
Spider-Man 3 with debug menu released for xbox 360 contains no debug information regarding function names, which is obvious since you weren't able to name any function. But magically `ngl*` functions were all named(incorrectly) and btw `SM3_NGL_DEFUALT_FONT` is `nglSysFont`. 

It's cool to see more work done on other spidey games but please respect the work other developers put in the same engine.

**Comment by AkyrosXD** [comment]
Hello,
I believe you got things mixed up. function names were just my guess by looking at the example at the function `0x8DAC90` because that function contains the box of the `Show Perf Info` and I used that as an example to draw the menu. 

The naming `ngl*` was taken from `nglPresent` when I was looking through the strings and it can be found at  the function `0x8CD650`. 

About the `nglSysFont`, I named things by guessing since I do not have access to any debug symbols.

Some parameters ofr NGL functions were reversed with trial and error.

Last but not least, it is normal for functions to not be named 100% accurately since the only way to guess the name is by looking at what they are doing (same with `nglSysFont` as I said above).

I looked at your menu and I do respect your work. But to be honest, I actually did everything by myself. The only exception is the `RGBA_TO_INT` which I took from the internet but was used on an older project and I do not remember where I took it from.

**Comment by krystalgamer** [comment]
> About the nglSysFont, I named things by guessing since I do not have access to any debug symbols.

You can find it in the retail version as "ngl_sysfont" and in the xbox 360 version as both ways.

> The only exception is the `RGBA_TO_INT` which I took from the internet

No idea why you took it from the internet, the function is either present or inlined depending on the situation.


My code is MIT licensed, you can do whatever you want with it, just give attribution.

/finished

A cool thing I noticed was your watermark, it's clearly inspired by mine which sole purpose was to piss off someone that I knew wanted to claim my work as his (and it worked).

I'd recommend you to fix your function names to the correct ones, it'd help people looking into these games. Besides that, please don't use `GetAsyncKeyState`, it captures even the window is not focused. Just hook the game's input handler.
